spring:
  datasource:
    # The JDBC driver class used by the data source.
    river-class-name: com.mysql.cj.jdbc.Driver
    # The URL for the database. Use the environment variable if it exists, otherwise use the default value.
    url: ${DB_MYSQL_URL:jdbc:mysql://localhost:3306/lv_database}
    # The username for the database. Use the environment variable if it exists, otherwise use the default value.
    username: ${DB_MYSQL_USERNAME:admin}
    # The password for the database. Use the environment variable if it exists, otherwise use the default value.
    password: ${DB_MYSQL_PASSWORD:admin}
  server:
    # Configuration for error handling.
    error:
      # Specifies when to include a stack trace in error responses. "never" means never include the stack trace.
      include-stacktrace: never
  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
        hbm2ddl:
          auto: update
  mail:
    host: ${MAIL_SMTP_HOST:smtp.gmail.com}
    username: ${MAIL_SMTP_USERNAME}
    password: ${MAIL_SMTP_PASSWORD}
    port: ${MAIL_SMTP_PORT:587}
    protocol: smtp
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

# Disables logging for the SqlExceptionHelper class.
logging:
  level:
    org.hibernate.engine.jdbc.spi.SqlExceptionHelper: OFF

app:
  client_base_url: ${CLIENT_BASE_URL:http://localhost:3000/}
  account_activation_url: ${ACCOUNT_ACTIVATION_URL:http://localhost:3000/activate-account/}
  password_recovery_url: ${PASSWORD_RECOVERY_URL:http://localhost:3000/forgot-password/}
  jwt:
    token:
      secret: ${JWT_SECRET:12345678}
      issuer: listvideo.app
    expiration-time-in-hours: ${JWT_EXPIRATION_TIME_IN_HOURS:1}